### ISSUE TITLE
Broadcast Flag for `signMultipleTransactions`

### ISSUE THREAD

**Issue by skyrover7** [secretkeylabs/sats-connect#68]
It would be super useful for the `signMultipleTransactions` to have a broadcast flag, similar to `signTransaction` so that one can easily sign and broadcast multiple psbts. 

On that note, are there any documented steps of taking the signed psbt returned from either method (`signTransaction` with broadcast `false` or `signMultipleTransactions`) and getting the hex that can be broadcast?

**Comment by victorkirov** [comment]
@skyrover7 it is pretty risky for us to undertake the broadcasting of multiple signed PSBTs as the user could close the wallet popup during the procedure. That's why we return the signed PSBTs and leave it up to the DAPP to broadcast the transactions either locally or via a server for safety (e.g. a user can close the browser window while some txns are still broadcasting).

It's pretty simple to parse the PSBTs and broadcast them once you have the signed PSBTs. Could you let me know which library you're using to create the transactions and I can send through some example code.

**Comment by skyrover7** [comment]
Thanks @victorkirov for the context! Was able to get it figured out as far as finalizing and broadcasting. The single sign was so nice and clean through the wallet to implement vs. having to manually broadcast, so just thought it was a missed opportunity.

**Comment by victorkirov** [comment]
We considered adding it but it just opens up the doors for misuse, so we leave it up to the devs to handle the broadcast. If you consider a scenario with a request for 100 PSBTs being signed with broadcast enabled, there are too many things that could go wrong with broadcasting directly from the wallet (e.g. 20 of the broadcasts succeed and 80 fail), so we decided to leave it up to the developers to handle it in a safe way.

Glad you got it working 😄 Can I close the ticket?

**Comment by skyrover7** [comment]
makes sense, yep closing it now
