### ISSUE TITLE
Get txId without broadcast

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#69]
I would like to request 2 features:

1. Signing raw txs in the format "02000000013cc4....0000000" (the one we get from BTC RPC)
2. Getting the txId after signing without being forced to broadcast

**Comment by victorkirov** [comment]
Hi @elRaulito 

Neither of these are really possible. A transaction can be converted to a BTC RPC compatible hex value only once they are finalised. It wouldn't be possible to finalise a transaction without it being signed first.

As for the txid without broadcasting, the same holds true. You cannot get a transaction's ID until it is finalised, so we only return it if we are broadcasting it (we would have to finalise it before). If the transaction is not marked for broadcasting, we don't finalise it because we can't be sure that there isn't more to be done with it. If it is ready to be finalised once it's returned from the wallet, you can build the transaction from the PSBT, finalise it, and then extract the txid from it.

**Comment by victorkirov** [comment]
Please reopen if you need more input.
