### ISSUE TITLE
Error while signing a PSBT 

### ISSUE THREAD

**Issue by elRaulito** [secretkeylabs/sats-connect#71]
I am following the tutorial at [link](https://dev.to/eunovo/unlocking-the-power-of-p2wsh-a-step-by-step-guide-to-creating-and-spending-coins-with-bitcoin-scripts-using-bitcoinjs-lib-a7o)

And I am at the point where using a script like this:
```
    const locking_script = script.compile([
    opcodes.OP_DUP,
    opcodes.OP_HASH160,
    crypto.hash160("028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd"),
    opcodes.OP_EQUALVERIFY,
    opcodes.OP_CHECKSIG
  ])
```

I got the address bc1qq3r80lygdgl3wmpa5rt9l57xfepr9hkf7728q090z75k38magfvqzdadt7

However in order to redeem I need to pass the sig in the witness therefore my first try was to sign the psbts that I get:

`cHNidP8BAFMCAAAAAcZjU/fLSzKbXfUah9mtfhp6DDjrK3mcY6Ea9I9il9/JAAAAAAD/////AWhCAAAAAAAAF6kUFMjwOBiDWXNvb7+ZpflEjRmAg0aHAAAAAAABASsgTgAAAAAAACIAIARGd/yIaj8XbD2g1l/Txk5CMt7J95RwPK8XqWiffUJYAQUZdqkUGzRXtbBbTTEngIq2QOEl/N8T6NeIrAAA`

however this error pops up and I can't proceed, probably I am missing something

![image](https://github.com/secretkeylabs/sats-connect/assets/42917076/e33faf19-817c-40ed-bba5-70f1530d1883)

**Comment by victorkirov** [comment]
I'll need a bit more info on this. From the looks of things, there is a mismatch between the public keys you're using in the script and the public key of the address you are signing with.

Also, the flow seems a bit off. If you want to create a p2sh/p2wsh address to spend from, you need to send funds to that address and spend from there. I would suggest testing this out in Testnet so that you don't waste real btc on failed attempts 😋

**Comment by elRaulito** [comment]
Thanks!

So yes I created the p2wsh address and sent funds there in this transaction `c9df97628ff41aa1639c792beb380c7a1a7eadd9871af55d9b324bcbf75363c6`

So I am trying to spend the funds from 

`c9df97628ff41aa1639c792beb380c7a1a7eadd9871af55d9b324bcbf75363c6` with index 0

The pubkey of the script showing in the popup is the bytecode of the script: 

```
   opcodes.OP_DUP,
    opcodes.OP_HASH160,
    crypto.hash160("028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd"),
    opcodes.OP_EQUALVERIFY,
    opcodes.OP_CHECKSIG
```
So I don't really have that pubkey because it's a script one

Maybe I should use nonWitnessUtxo for this and sign? 

I need to sign because the witnessRedeem needs the signature as parameter to finish the psbts

Thanks in advance @victorkirov

**Comment by victorkirov** [comment]
I think you might have a bug in the script. `crypto.hash160` takes in a Buffer, not a string.

Try use `crypto.hash160(Buffer.from("028f5ced5649da371758f280635f94a558c68eee2ac4c7f07034425e97c60352bd", "hex"))` instead. I'm not sure why they don't validate the input in that function since it silently works with a string input 😅

**Comment by victorkirov** [comment]
Just to note, that is the public key you got back from the getAddress function from sats-connect, right? If so, then the above fix should work, but the funds you sent to the other address won't be recoverable.

I strongly suggest you test this out on testnet before committing to it on mainnet.

**Comment by elRaulito** [comment]
@victorkirov Thanks a lot, that made the thing

I switched to testnet now for further testes, thanks again

Now I can unlock funds from script addresses

**Comment by victorkirov** [comment]
Awesome 😎 Glad it's working. I'm gonna close the ticket, feel free to reopen if needed.
